/*
 * This source file was generated by the Gradle 'init' task
 */
package com.unyaunya.minic;

import java.nio.file.Paths;
import java.util.logging.Logger;

import org.antlr.v4.runtime.CharStream;
import org.antlr.v4.runtime.CharStreams;
import org.antlr.v4.runtime.CommonTokenStream;

import com.unyaunya.minic.frontend.AstBuilder;
import com.unyaunya.minic.parser.MiniCLexer;
import com.unyaunya.minic.parser.MiniCParser;
import com.unyaunya.minic.parser.MiniCParser.ProgramContext;

public class CompilerMain {
    Logger logger = Logger.getLogger(getClass().getName());    
    
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        if (args.length < 1) {
            System.err.println("Usage: minic <source.mc>");
            System.exit(1);
        }

        CharStream input = CharStreams.fromPath(Paths.get(args[0]));
        MiniCLexer lexer = new MiniCLexer(input);
        CommonTokenStream tokens = new CommonTokenStream(lexer);
        MiniCParser parser = new MiniCParser(tokens);

        ProgramContext tree = parser.program(); // entry rule

        AstBuilder builder = new AstBuilder();
        Expr ast = (Expr) builder.visit(tree);

        SemanticAnalyzer sema = new SemanticAnalyzer();
        sema.check(ast); // throws on error

        Casl2Emitter emitter = new Casl2Emitter();
        String asm = emitter.emit(ast);

        System.out.println(asm);
    }
}
