/*
 * This source file was generated by the Gradle 'init' task
 */
package com.unyaunya.minic;

import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.logging.Logger;

import org.antlr.v4.runtime.CharStream;
import org.antlr.v4.runtime.CharStreams;
import org.antlr.v4.runtime.CommonTokenStream;

import com.unyaunya.minic.backend.Casl2Emitter;
import com.unyaunya.minic.frontend.AstBuilder;
import com.unyaunya.minic.frontend.Program;
import com.unyaunya.minic.parser.MiniCLexer;
import com.unyaunya.minic.parser.MiniCParser;
import com.unyaunya.minic.parser.MiniCParser.ProgramContext;
import com.unyaunya.minic.preprocess.Preprocessor;
import com.unyaunya.minic.semantics.SemanticAnalyzer;
import com.unyaunya.minic.semantics.SemanticInfo;

public class CompilerMain {
    private Logger logger = Logger.getLogger(getClass().getName());    
    
    public String compile(String path) throws MinicException {
        return compile(Paths.get(path));
    }

    public String compile(Path path) throws MinicException {
        // Preprocess includes so we can map combined line numbers back to filenames
        Preprocessor pre = new Preprocessor();
        Preprocessor.Result res = pre.preprocess(path);

        CharStream input = CharStreams.fromString(res.content);
        MiniCLexer lexer = new MiniCLexer(input);
        CommonTokenStream tokens = new CommonTokenStream(lexer);
        tokens.fill();
        MiniCParser parser = new MiniCParser(tokens);

        ProgramContext tree = parser.program(); // entry rule

        AstBuilder builder = new AstBuilder(res);
        Program ast = (Program) builder.visit(tree);

        SemanticAnalyzer sema = new SemanticAnalyzer();
        SemanticInfo semanticInfo = sema.analyze(ast); // throws on error

        Casl2Emitter emitter = new Casl2Emitter();
        return emitter.emit(ast, semanticInfo, 1024);
    }

     public void run(String[] args) throws MinicException {
        if (args.length < 1) {
            logger.severe("Usage: minic <source.mc>");
            System.exit(1);
        }
        String asm = this.compile(args[0]);
        if (args.length > 1) {
            String filePath = args[1];
            try (FileWriter writer = new FileWriter(filePath)) {
                writer.write(asm);
            } catch (IOException e) {
                e.printStackTrace();
            }
        } else {
            logger.info(asm);
        }
    }

    public static void main(String[] args) throws MinicException {
        new CompilerMain().run(args);
    }
}
