/*
 * This source file was generated by the Gradle 'init' task
 */
package com.unyaunya.minic;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class CompilerMainTest {
    @Test void appHasAGreeting() {
        CompilerMain classUnderTest = new CompilerMain();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
