/*
 * This source file was generated by the Gradle 'init' task
 */
package com.unyaunya.minic;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.io.IOException;
import java.net.URISyntaxException;
import java.nio.file.Path;

class CompilerMainTest {
    @Test
    void compileTest() throws IOException, URISyntaxException {
        Path path = getPath("test1.mc");
        String asm = CompilerMain.compile(path);
        System.out.print(asm);
        assertEquals("""
            START
            END
                """, asm);
    }

    Path getPath(String path) throws URISyntaxException {
        return Path.of(getClass().getClassLoader().getResource(path).toURI());
    }   


}
